CREATE TABLE IF NOT EXISTS `USER` (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(50) NOT NULL,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL
);